backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "index page"
        name: "home"
        file: "src/content/home.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro text, name: intro, widget: text }
          - { label: Image, name: image, widget: image }

      - label: "About Page"
        name: "about"
        file: "src/content/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description text, name: description, widget: text }
          - { label: Image, name: aboutimage, widget: image }

  - name: "music"
    label: "Music"
    description: "Music, mixes, videos"
    slug: "{{title}}"
    folder: "src/content/music"
    create: true
    fields:
      - { label: "Title", name: "title", widget: string }
      - { label: "Artwork", name: "art", widget: image }
      - { label: "Link", name: "link", widget: string }

  - name: "shows"
    label: "Shows"
    descripton: "Upcoming Shows"
    slug: "{{venue}} show"
    folder: "src/content/shows"
    create: true
    fields:
      - { label: "Venue", name: "venue", widget: string }
      - { label: "City", name: "city", widget: string }
      - {
          label: "Date and time",
          name: "datetime",
          widget: datetime,
          dateFormate: "DD.MM.YYYY",
          timeFormat: "HH:mm",
          format: "LLL",
        }
      - { label: "Tickets Link", name: "link", widget: string }
